name: Update

on:
  workflow_dispatch:

jobs:
  update-deno-module:
    permissions:
      contents: read
      pull-requests: write
    uses: skanehira/actions/.github/workflows/uud.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
