name: Update

on:
  workflow_dispatch:

jobs:
  udd:
    runs-on: ubuntu-latest
    # for using uud action
    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: skanehira/actions/.github/actions/uud@main
        id: uud
      - uses: peter-evans/create-pull-request@v6
        if: steps.uud.outputs.content != ''
        with:
          title: ":package: Update Deno dependencies"
          body: |
            ```
            ${{ steps.uud.outputs.content }}
            ```
          labels: automation
          branch: automation/update-dependencies
